name: The Greeter pipeline

on:
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up python
                uses: actions/setup-python@v4
                with:
                        python-version: '3.9'
            
            -   name: Install dependencies
                run: pip install Flask
                
            -   name: Run tests
                run: |
                    chmod +x ./scripts/health-check-test.sh && chmod +x ./scripts/build.sh
                    ./scripts/health-check-test.sh
                    ./scripts/build.sh
    
    build-and-push:
        name: Build and push docker image
        needs: test
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            
            -   name: Log into Dockerhub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Extract version
                id: get_version
                run: echo "APP_VERSION=$(cat VERSION)" >> $GITHUB_ENV

            -   name: Docker meta creator
                id: meta
                uses: docker/metadata-action@v5
                with:
                      images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/the-greeter
                      tags: |
                        type=raw,value=${{ env.APP_VERSION }}
                        type=raw,value=latest

            -   name: Build and push Docker image
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
